# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  roziseth01

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install --save-dev mocha-junit-reporter@2.0.2
    npm install --save-dev nyc@15.1.0
    npm audit fix
    npm test
  displayName: 'npm install and test'
